# Generated by Django 5.1.1 on 2024-10-09 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagementapp', '0002_collection_engagementpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='posts',
            field=models.ManyToManyField(related_name='collections', to='engagementapp.engagementpost'),
        ),
        migrations.AddField(
            model_name='engagementpost',
            name='thumbnail_title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
        migrations.AddField(
            model_name='engagementpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='SKU',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='EngagementPostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagementapp.engagementpost')),
            ],
        ),
    ]
