# Generated by Django 5.1.1 on 2024-10-09 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagementapp', '0003_collection_posts_engagementpost_thumbnail_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementpostcontent',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='engagementapp.engagementpost'),
        ),
        migrations.CreateModel(
            name='EngagementPostProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='engagementapp.engagementpost')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagementapp.product')),
            ],
        ),
    ]
